version: "1"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: jenkins/jenkins:lts
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.4"
          memory: 1024M
      restart_policy:
        condition: on-failure
    ports:
      - "8092:8080"
    networks:
      - jenkinsnet
networks:
  jenkinsnet:
