version: "3"
services:
  jenkins:
    image: openhmis/jenkins:lts
    ports:
      - "9003:8080"
    networks:
      - jenkinsnet
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://localhost:8080/"]
      interval: 1m30s
      timeout: 5s
      retries: 3

volumes:
    jenkins_home:
        external: true
networks:
  jenkinsnet:
